name: SIG
favicon: null
layout_spectrum: 1
typography_spectrum: 0.25764
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#60411f'
    - '#c9d747'
    - '#6a9448'
    - '#000000'
    - '#ffff00'
  brandStrength: 0.8125
  lightness: 0.6629671414848417
  saturation: 0.1501841761637479
  rhythmicContrast: 0.9509900412522256
purpose: []
